- name: Deploy Docker and Nginx with custom configurations
  hosts: all
  become: true  # Ensure sudo or root privileges are used
  vars_files:
    - vars/main.yml

  roles: 
    - install 
    - deploy
