---
# tasks file for deploy
- name: Install docker 
  include_tasks: install_docker.yml
  tags:
    - docker_installation

- name: Install Portainer Docker container
  docker_container:
    name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    restart_policy: always
    env:
      ADMIN_USERNAME: "{{ portainer_credentials.ADMIN_USERNAME }}"
      ADMIN_PASS: "{{ portainer_credentials.ADMIN_PASS }}" # Replace with your desired password 
  become: true
  tags:
    - portainer

  

- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: true
  tags:
    - nginx

# tasks file for deploy-webmin
- name: Install python-apt
  apt:
    name: python3-apt
    state: present
  tags:
    - webmin


- name: Install prerequisites
  apt:
    name:
      - perl 
      - libnet-ssleay-perl 
      - openssl 
      - libauthen-pam-perl
      - libpam-runtime
      - libio-pty-perl
      - python3
      - libwww-perl
      - liblwp-protocol-https-perl
    state: latest
    update_cache: yes
  tags:
    - webmin

- name: Add key for Webmin repository
  apt_key:
    url: https://www.webmin.com/jcameron-key.asc
    state: present
  tags:
    - webmin

- name: Add Webmin repository
  apt_repository:
    repo: 'deb https://download.webmin.com/download/repository sarge contrib'
    state: present
    filename: webmin
    update_cache: yes
  tags:
    - webmin

- name: Install/Update Webmin
  apt:
    name: 
      - webmin
    state: latest
  register: webmin_check
  tags:
    - webmin


- name: Check if Webmin service is running
  service:
    name: webmin
    state: started
  register: webmin_service
  ignore_errors: yes
  tags:
    - webmin
    - check_webmin


- name: Debug Webmin service status
  debug:
    msg: "webmin {{ webmin_service.state }}"
  tags:
    - webmin
    - debug_webmin
