   # webmin_vars 
    webmin_port: 10001
    # container_d vars
    subnet: "172.16.2.0/24"
    network_name: "myapp_network"
    containers:
      - container_name: "mynginx_3"
        container_image: "nginx"
        container_ports: "8090:80"
      - container_name: "mynginx_4"
        container_image: "nginx"
        container_ports: "8070:80"
       
    # nginx vars
    nginx_configs:
      - name: nginx_config1
        server_name: example.com
        proxy_pass: http://backend1
      - name: nginx_config2
        server_name: test.com
        proxy_pass: http://backend2

    portainer_credentials:
      ADMIN_USERNAME: "admin"
      ADMIN_PASS: "admin1234567890"